export function createDOMRefs() {
  return {
    app: document.querySelector("#app"),
    leftPanelShell: document.querySelector("#left-panel-shell"),
    rightPanelShell: document.querySelector("#right-panel-shell"),
    leftPanelToggleBtn: document.querySelector("#left-panel-toggle"),
    rightPanelToggleBtn: document.querySelector("#right-panel-toggle"),
    statusModelEl: document.querySelector("#status-model"),
    statusHDREl: document.querySelector("#status-hdr"),
    statusSelectionEl: document.querySelector("#status-selection"),
    objectListEl: document.querySelector("#object-list"),
    materialInspectorEl: document.querySelector("#material-inspector"),
    basicInfoInspectorEl: document.querySelector("#basic-info-inspector"),
    lightInspectorEl: document.querySelector("#light-inspector"),
    tabButtons: document.querySelectorAll("[data-tab-target]"),
    tabPanels: document.querySelectorAll("[data-tab-panel]"),
    showDemoBtn: document.querySelector("#show-demo-btn"),
    pickGLBBtn: document.querySelector("#pick-glb-btn"),
    loadDefaultHDRBtn: document.querySelector("#load-default-hdr-btn"),
    pickHDRBtn: document.querySelector("#pick-hdr-btn"),
    resetViewBtn: document.querySelector("#reset-view-btn"),
    clearSelectionBtn: document.querySelector("#clear-selection-btn"),
    toggleMoveBtn: document.querySelector("#toggle-move-btn"),
    showAllBtn: document.querySelector("#show-all-btn"),
    moveSpeedRange: document.querySelector("#move-speed-range"),
    moveSpeedValueEl: document.querySelector("#move-speed-value"),
    glbInput: document.querySelector("#glb-input"),
    hdrInput: document.querySelector("#hdr-input"),
  };
}
